/**
 * Fail if a question that needs something to READ -- a map, a graph, a table,
 * a figure -- can reach practice without it.
 *
 * Some paper items were written against a map or graph that was never entered:
 * "Write down the grid reference of the clinic" with no map, "The graph of f
 * ... Determine the values of a, b and q" with no graph. They are unanswerable
 * in the paper and out of it. Until the picture is drawn, they are listed in
 * src/data/awaitingStimulus.ts, and the question bank keeps them out of
 * practice, worksheets and tests.
 *
 * What counts as needing one: the question (or the context it carries, see
 * sharedStimulus.ts) names a map, TABLE n, FIGURE n or "shown below", or reads from "the graph"/"the diagram" -- unless it gives an equation to
 * work from, or asks the learner to draw or sketch it. What counts as having
 * one: a table in the context, or a graph, figure, chart or circuit on the
 * item or an earlier sub-question.
 *
 *   npm run check:missing-stimulus            -- check
 *   npm run check:missing-stimulus -- --write  -- rewrite the list
 */
import fs from 'fs'
import { papersForSubject } from '../src/data/papers/index.ts'
import { withSectionStimulus } from '../src/data/sharedStimulus.ts'
import { derivedGraphs } from '../src/data/derivedGraphs.ts'
import { derivedFigures } from '../src/data/derivedFigures.ts'
import { derivedCircuits } from '../src/data/derivedCircuits.ts'
import { chartSpecs } from '../src/data/chartSpecs.ts'
import { awaitingStimulus } from '../src/data/awaitingStimulus.ts'

const NAMED = /\b(TABLE\s*\d+|shown below|given below|below shows|the map|this map|on the map|FIGURE\s*\d+)\b/i
const READS = /\b(the graph|the sketch|the diagram)\b/i
const WORKS_FROM_EQUATION = /=|\bpasses through\b/
const ASKS_TO_DRAW = /\b(sketch|draw|describe|in words)\b/i
const visual = (id: string) => derivedGraphs[id] || derivedFigures[id] || derivedCircuits[id] || chartSpecs[id]?.chart

const found: { id: string; why: string }[] = []
for (const subject of ['mat-lit', 'mathematics', 'physical-sciences', 'life-sciences']) {
  for (const p of await papersForSubject(subject))
    for (const s of p.sections)
      for (const q of withSectionStimulus(s.items)) {
        const text = `${q.context ?? ''}\n${q.prompt}`
        const hasTable = /^\s*\|/m.test(q.context ?? '')
        const hasVisual = q.graph || q.figure || q.chart || q.circuit || visual(q.id) || (q.stimulusIds ?? []).some(visual)
        if (hasTable || hasVisual) continue
        const named = text.match(NAMED)
        const reads = !named && READS.test(text) && !WORKS_FROM_EQUATION.test(text) && !ASKS_TO_DRAW.test(q.prompt) ? text.match(READS) : null
        const m = named ?? reads
        if (m) found.push({ id: q.id, why: m[0] })
      }
}
found.sort((a, b) => a.id.localeCompare(b.id))

if (process.argv.includes('--write')) {
  const body = found.map((f) => `  '${f.id}', // ${f.why}`).join('\n')
  fs.writeFileSync(
    new URL('../src/data/awaitingStimulus.ts', import.meta.url),
    `/**\n * Paper items that need a map, graph, table or figure that has not been\n * entered yet. They stay in their papers; the question bank keeps them out\n * of practice, worksheets and tests until the picture exists. Generated by\n * tools/check-missing-stimulus.mts -- draw the picture, then run it with\n * --write to take an item off this list.\n */\nexport const awaitingStimulus = new Set<string>([\n${body}\n])\n`,
  )
  console.log(`Wrote ${found.length} item(s) to src/data/awaitingStimulus.ts.`)
} else {
  const missing = found.filter((f) => !awaitingStimulus.has(f.id))
  if (missing.length) {
    for (const f of missing) console.error(`  ${f.id}: refers to ${f.why}, which it does not have`)
    console.error(`\n${missing.length} question(s) need a map, graph, table or figure they do not have. Add it, or run with --write to keep them out of practice.`)
    process.exit(1)
  }
  console.log(`Every question that needs something to read has it (${awaitingStimulus.size} held back until drawn).`)
}
