/**
 * Paper items that need a map, graph, table or figure that has not been
 * entered yet. They stay in their papers; the question bank keeps them out
 * of practice, worksheets and tests until the picture exists. Generated by
 * tools/check-missing-stimulus.mts -- draw the picture, then run it with
 * --write to take an item off this list.
 */
export const awaitingStimulus = new Set<string>([

])
