/* GENERATED by tools/derive-graphs.mts -- do not edit by hand.
 *
 * Each entry is a graph derived from the equation the question itself states,
 * and verified against it: see src/data/graphSpecs.ts. Regenerate with
 * `npm run graphs:write`; `npm run check:graphs` fails if this file has
 * drifted from the corpus.
 */
import type { GraphSpec } from '@/types'

/** Shown beside the question: reading questions, where the picture IS the task. */
export const derivedGraphs: Record<string, GraphSpec> = {
  "math-g10-p1-22-4-12": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -16,
      24
    ],
    "curves": [
      {
        "kind": "line",
        "m": 2,
        "c": 4
      }
    ]
  },
  "math-g10-p1-24-4-12": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      2
    ],
    "yRange": [
      -1,
      5
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 0,
        "c": 0
      }
    ]
  },
  "math-g10-p1-a-4-12": {
    "title": "The graph of g",
    "xRange": [
      -7,
      7
    ],
    "yRange": [
      -18,
      18
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 16,
        "p": 0,
        "q": 0,
        "label": "g"
      }
    ]
  },
  "math-g10-p1-b-4-12": {
    "title": "The graphs in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -19,
      13
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": -1,
        "b": 0,
        "c": 9,
        "label": "f"
      },
      {
        "kind": "line",
        "m": 1,
        "c": 3,
        "label": "g"
      }
    ]
  },
  "math-g10-p1-c-4-12": {
    "title": "The graph of f",
    "xRange": [
      -1,
      7
    ],
    "yRange": [
      -6,
      14
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -6,
        "c": 5,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-20-4-10": {
    "title": "The graph of f",
    "xRange": [
      -14,
      14
    ],
    "yRange": [
      -124,
      120
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 0,
        "c": -100,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-21-4-10": {
    "title": "The graph of f",
    "xRange": [
      -13,
      13
    ],
    "yRange": [
      -102,
      109
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 0,
        "c": -81,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-22-4-10": {
    "title": "The graph of f",
    "xRange": [
      -12,
      12
    ],
    "yRange": [
      -82,
      98
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 0,
        "c": -64,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-23-4-10": {
    "title": "The graph of f",
    "xRange": [
      -10,
      10
    ],
    "yRange": [
      -61,
      63
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 0,
        "c": -49,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-24-4-10": {
    "title": "The graph of f",
    "xRange": [
      -9,
      9
    ],
    "yRange": [
      -46,
      55
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 0,
        "c": -36,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-25-4-10": {
    "title": "The graph of f",
    "xRange": [
      -1,
      6
    ],
    "yRange": [
      -3,
      17
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -6,
        "c": 8,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-a-4-10": {
    "title": "The graph of f",
    "xRange": [
      -5,
      5
    ],
    "yRange": [
      -12,
      19
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 0,
        "c": -9,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-b-4-10": {
    "title": "The graph of f",
    "xRange": [
      -7,
      7
    ],
    "yRange": [
      -22,
      39
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 0,
        "c": -16,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-c-4-10": {
    "title": "The graph of f",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -33,
      47
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 0,
        "c": -25,
        "label": "f"
      }
    ]
  },
  "math-p1-20-4-8": {
    "title": "The graph of f",
    "xRange": [
      -14,
      14
    ],
    "yRange": [
      -124,
      120
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 0,
        "c": -100,
        "label": "f"
      }
    ]
  },
  "math-p1-21-4-8": {
    "title": "The graph of f",
    "xRange": [
      -13,
      13
    ],
    "yRange": [
      -102,
      109
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 0,
        "c": -81,
        "label": "f"
      }
    ]
  },
  "math-p1-22-4-8": {
    "title": "The graph of f",
    "xRange": [
      -12,
      12
    ],
    "yRange": [
      -82,
      98
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 0,
        "c": -64,
        "label": "f"
      }
    ]
  },
  "math-p1-23-4-8": {
    "title": "The graph of f",
    "xRange": [
      -10,
      10
    ],
    "yRange": [
      -61,
      63
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 0,
        "c": -49,
        "label": "f"
      }
    ]
  },
  "math-p1-23-5-5": {
    "title": "The graph of f",
    "xRange": [
      -5,
      5
    ],
    "yRange": [
      -170,
      30
    ],
    "curves": [
      {
        "kind": "cubic",
        "a": 1,
        "b": -3,
        "c": -9,
        "d": 5,
        "label": "f"
      }
    ]
  },
  "math-p1-24-4-8": {
    "title": "The graph of f",
    "xRange": [
      -9,
      9
    ],
    "yRange": [
      -46,
      55
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 0,
        "c": -36,
        "label": "f"
      }
    ]
  },
  "math-p1-25-4-7": {
    "title": "The graph in this question",
    "xRange": [
      -4,
      5
    ],
    "yRange": [
      -4,
      22
    ],
    "curves": [
      {
        "kind": "exponential",
        "a": 1,
        "b": 2,
        "q": 0
      }
    ]
  },
  "math-p1-25-4-8": {
    "title": "The graph of f",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -33,
      47
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 0,
        "c": -25,
        "label": "f"
      }
    ]
  },
  "math-p1-a-4-7": {
    "title": "The graph of g",
    "xRange": [
      -4,
      5
    ],
    "yRange": [
      -4,
      22
    ],
    "curves": [
      {
        "kind": "exponential",
        "a": 1,
        "b": 2,
        "q": 0,
        "label": "g"
      }
    ]
  },
  "math-p1-a-4-8": {
    "title": "The graph of f",
    "xRange": [
      -4,
      4
    ],
    "yRange": [
      -6,
      14
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 0,
        "c": -4,
        "label": "f"
      }
    ]
  },
  "math-p1-b-4-8": {
    "title": "The graph of f",
    "xRange": [
      -5,
      5
    ],
    "yRange": [
      -12,
      19
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 0,
        "c": -9,
        "label": "f"
      }
    ]
  },
  "math-p1-c-4-8": {
    "title": "The graph of f",
    "xRange": [
      -7,
      7
    ],
    "yRange": [
      -22,
      39
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 0,
        "c": -16,
        "label": "f"
      }
    ]
  },
  "mth-cubic-2": {
    "title": "The graph of g",
    "xRange": [
      -5,
      5
    ],
    "yRange": [
      -61,
      361
    ],
    "curves": [
      {
        "kind": "cubic",
        "a": -1,
        "b": 6,
        "c": -9,
        "d": 0,
        "label": "g"
      }
    ]
  },
  "mth-explog-1": {
    "title": "The graph of f",
    "xRange": [
      -4,
      3
    ],
    "yRange": [
      -5,
      34
    ],
    "curves": [
      {
        "kind": "exponential",
        "a": 2,
        "b": 3,
        "q": 0,
        "label": "f"
      }
    ]
  },
  "mth-transf-3": {
    "title": "The graph of f",
    "xRange": [
      -2,
      2
    ],
    "yRange": [
      -1,
      5
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 0,
        "c": 0,
        "label": "f"
      }
    ]
  }
}

/** Shown only with the revealed answer: finding questions, where the picture
 *  would otherwise do the learner's work for them. */
export const derivedAnswerGraphs: Record<string, GraphSpec> = {
  "gap-g11-simul-two-graphs": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -13,
      7
    ],
    "curves": [
      {
        "kind": "line",
        "m": 1,
        "c": -3
      }
    ]
  },
  "math-g10-p1-20-4-1-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -22,
      18
    ],
    "curves": [
      {
        "kind": "line",
        "m": 2,
        "c": -2
      }
    ]
  },
  "math-g10-p1-20-4-2": {
    "title": "The graph of f",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -22,
      3
    ],
    "curves": [
      {
        "kind": "line",
        "m": 1,
        "c": -11,
        "label": "f"
      }
    ]
  },
  "math-g10-p1-20-4-3": {
    "title": "The graph of f",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -22,
      3
    ],
    "curves": [
      {
        "kind": "line",
        "m": 1,
        "c": -11,
        "label": "f"
      }
    ]
  },
  "math-g10-p1-20-4-4": {
    "title": "The graph of g",
    "xRange": [
      -4,
      14
    ],
    "yRange": [
      -46,
      55
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -10,
        "c": -11,
        "label": "g"
      }
    ]
  },
  "math-g10-p1-20-4-4-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -22,
      18
    ],
    "curves": [
      {
        "kind": "line",
        "m": 2,
        "c": -2
      }
    ]
  },
  "math-g10-p1-20-4-5": {
    "title": "The graph of g",
    "xRange": [
      -4,
      14
    ],
    "yRange": [
      -46,
      55
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -10,
        "c": -11,
        "label": "g"
      }
    ]
  },
  "math-g10-p1-20-4-9": {
    "title": "The graph of p",
    "xRange": [
      -2,
      16
    ],
    "yRange": [
      -2,
      16
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 9,
        "p": 9,
        "q": 8,
        "label": "p"
      }
    ]
  },
  "math-g10-p1-21-4-12": {
    "title": "The graphs in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -30,
      30
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 0,
        "c": -4,
        "label": "f"
      },
      {
        "kind": "line",
        "m": 3,
        "c": 0,
        "label": "g"
      }
    ]
  },
  "math-g10-p1-21-4-2": {
    "title": "The graph of f",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -21,
      3
    ],
    "curves": [
      {
        "kind": "line",
        "m": 1,
        "c": -10,
        "label": "f"
      }
    ]
  },
  "math-g10-p1-21-4-2-r": {
    "title": "The graph in this question",
    "xRange": [
      -7,
      7
    ],
    "yRange": [
      -8,
      1
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 2,
        "p": 0,
        "q": -5
      }
    ]
  },
  "math-g10-p1-21-4-3": {
    "title": "The graph of f",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -21,
      3
    ],
    "curves": [
      {
        "kind": "line",
        "m": 1,
        "c": -10,
        "label": "f"
      }
    ]
  },
  "math-g10-p1-21-4-4": {
    "title": "The graph of g",
    "xRange": [
      -4,
      13
    ],
    "yRange": [
      -39,
      51
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -9,
        "c": -10,
        "label": "g"
      }
    ]
  },
  "math-g10-p1-21-4-4-r": {
    "title": "The graph in this question",
    "xRange": [
      -4,
      6
    ],
    "yRange": [
      -9,
      22
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -2,
        "c": -5
      }
    ]
  },
  "math-g10-p1-21-4-5": {
    "title": "The graph of g",
    "xRange": [
      -4,
      13
    ],
    "yRange": [
      -39,
      51
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -9,
        "c": -10,
        "label": "g"
      }
    ]
  },
  "math-g10-p1-21-4-9": {
    "title": "The graph of p",
    "xRange": [
      -2,
      15
    ],
    "yRange": [
      -2,
      13
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 6,
        "p": 8,
        "q": 7,
        "label": "p"
      }
    ]
  },
  "math-g10-p1-22-4-2": {
    "title": "The graph of f",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -20,
      3
    ],
    "curves": [
      {
        "kind": "line",
        "m": 1,
        "c": -9,
        "label": "f"
      }
    ]
  },
  "math-g10-p1-22-4-2-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -32,
      28
    ],
    "curves": [
      {
        "kind": "line",
        "m": 3,
        "c": -2
      }
    ]
  },
  "math-g10-p1-22-4-3": {
    "title": "The graph of f",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -20,
      3
    ],
    "curves": [
      {
        "kind": "line",
        "m": 1,
        "c": -9,
        "label": "f"
      }
    ]
  },
  "math-g10-p1-22-4-4": {
    "title": "The graph of g",
    "xRange": [
      -4,
      12
    ],
    "yRange": [
      -33,
      47
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -8,
        "c": -9,
        "label": "g"
      }
    ]
  },
  "math-g10-p1-22-4-4-r": {
    "title": "The graph in this question",
    "xRange": [
      -6,
      8
    ],
    "yRange": [
      -8,
      1
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 2,
        "p": 1,
        "q": -5
      }
    ]
  },
  "math-g10-p1-22-4-5": {
    "title": "The graph of g",
    "xRange": [
      -4,
      12
    ],
    "yRange": [
      -33,
      47
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -8,
        "c": -9,
        "label": "g"
      }
    ]
  },
  "math-g10-p1-22-4-9": {
    "title": "The graph of p",
    "xRange": [
      -2,
      14
    ],
    "yRange": [
      -2,
      14
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 8,
        "p": 7,
        "q": 6,
        "label": "p"
      }
    ]
  },
  "math-g10-p1-23-4-2": {
    "title": "The graph of f",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -18,
      2
    ],
    "curves": [
      {
        "kind": "line",
        "m": 1,
        "c": -8,
        "label": "f"
      }
    ]
  },
  "math-g10-p1-23-4-3": {
    "title": "The graph of f",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -18,
      2
    ],
    "curves": [
      {
        "kind": "line",
        "m": 1,
        "c": -8,
        "label": "f"
      }
    ]
  },
  "math-g10-p1-23-4-4": {
    "title": "The graph of g",
    "xRange": [
      -4,
      11
    ],
    "yRange": [
      -27,
      43
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -7,
        "c": -8,
        "label": "g"
      }
    ]
  },
  "math-g10-p1-23-4-4-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -32,
      28
    ],
    "curves": [
      {
        "kind": "line",
        "m": 3,
        "c": -2
      }
    ]
  },
  "math-g10-p1-23-4-5": {
    "title": "The graph of g",
    "xRange": [
      -4,
      11
    ],
    "yRange": [
      -27,
      43
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -7,
        "c": -8,
        "label": "g"
      }
    ]
  },
  "math-g10-p1-23-4-9": {
    "title": "The graph of p",
    "xRange": [
      -2,
      13
    ],
    "yRange": [
      -1,
      10
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 4,
        "p": 6,
        "q": 5,
        "label": "p"
      }
    ]
  },
  "math-g10-p1-24-4-1-r": {
    "title": "The graph in this question",
    "xRange": [
      -7,
      7
    ],
    "yRange": [
      -9,
      1
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 3,
        "p": 0,
        "q": -5
      }
    ]
  },
  "math-g10-p1-24-4-2": {
    "title": "The graph of f",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -17,
      3
    ],
    "curves": [
      {
        "kind": "line",
        "m": 1,
        "c": -7,
        "label": "f"
      }
    ]
  },
  "math-g10-p1-24-4-3": {
    "title": "The graph of f",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -17,
      3
    ],
    "curves": [
      {
        "kind": "line",
        "m": 1,
        "c": -7,
        "label": "f"
      }
    ]
  },
  "math-g10-p1-24-4-4": {
    "title": "The graph of g",
    "xRange": [
      -4,
      10
    ],
    "yRange": [
      -22,
      39
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -6,
        "c": -7,
        "label": "g"
      }
    ]
  },
  "math-g10-p1-24-4-4-r": {
    "title": "The graph in this question",
    "xRange": [
      -3,
      7
    ],
    "yRange": [
      -9,
      22
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -4,
        "c": -2
      }
    ]
  },
  "math-g10-p1-24-4-5": {
    "title": "The graph of g",
    "xRange": [
      -4,
      10
    ],
    "yRange": [
      -22,
      39
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -6,
        "c": -7,
        "label": "g"
      }
    ]
  },
  "math-g10-p1-24-4-9": {
    "title": "The graph of p",
    "xRange": [
      -2,
      12
    ],
    "yRange": [
      -3,
      11
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 6,
        "p": 5,
        "q": 4,
        "label": "p"
      }
    ]
  },
  "math-g10-p1-25-4-1-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -42,
      38
    ],
    "curves": [
      {
        "kind": "line",
        "m": 4,
        "c": -2
      }
    ]
  },
  "math-g10-p1-25-4-2": {
    "title": "The graph of f",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -16,
      4
    ],
    "curves": [
      {
        "kind": "line",
        "m": 1,
        "c": -6,
        "label": "f"
      }
    ]
  },
  "math-g10-p1-25-4-3": {
    "title": "The graph of f",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -16,
      4
    ],
    "curves": [
      {
        "kind": "line",
        "m": 1,
        "c": -6,
        "label": "f"
      }
    ]
  },
  "math-g10-p1-25-4-4": {
    "title": "The graph of g",
    "xRange": [
      -4,
      9
    ],
    "yRange": [
      -18,
      36
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -5,
        "c": -6,
        "label": "g"
      }
    ]
  },
  "math-g10-p1-25-4-4-r": {
    "title": "The graph in this question",
    "xRange": [
      -5,
      9
    ],
    "yRange": [
      -9,
      1
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 3,
        "p": 2,
        "q": -5
      }
    ]
  },
  "math-g10-p1-25-4-5": {
    "title": "The graph of g",
    "xRange": [
      -4,
      9
    ],
    "yRange": [
      -18,
      36
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -5,
        "c": -6,
        "label": "g"
      }
    ]
  },
  "math-g10-p1-25-4-9": {
    "title": "The graph of p",
    "xRange": [
      -3,
      11
    ],
    "yRange": [
      -3,
      9
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 5,
        "p": 4,
        "q": 3,
        "label": "p"
      }
    ]
  },
  "math-g10-p1-a-4-2": {
    "title": "The graph of f",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -13,
      7
    ],
    "curves": [
      {
        "kind": "line",
        "m": 1,
        "c": -3,
        "label": "f"
      }
    ]
  },
  "math-g10-p1-a-4-2-r": {
    "title": "The graph in this question",
    "xRange": [
      -7,
      7
    ],
    "yRange": [
      -10,
      2
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 4,
        "p": 0,
        "q": -5
      }
    ]
  },
  "math-g10-p1-a-4-3": {
    "title": "The graph of f",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -13,
      7
    ],
    "curves": [
      {
        "kind": "line",
        "m": 1,
        "c": -3,
        "label": "f"
      }
    ]
  },
  "math-g10-p1-a-4-4": {
    "title": "The graph of g",
    "xRange": [
      -3,
      5
    ],
    "yRange": [
      -6,
      14
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -2,
        "c": -3,
        "label": "g"
      }
    ]
  },
  "math-g10-p1-a-4-4-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -42,
      38
    ],
    "curves": [
      {
        "kind": "line",
        "m": 4,
        "c": -2
      }
    ]
  },
  "math-g10-p1-a-4-5": {
    "title": "The graph of g",
    "xRange": [
      -3,
      5
    ],
    "yRange": [
      -6,
      14
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -2,
        "c": -3,
        "label": "g"
      }
    ]
  },
  "math-g10-p1-a-4-9": {
    "title": "The graph of p",
    "xRange": [
      -6,
      8
    ],
    "yRange": [
      -1,
      6
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 2,
        "p": 1,
        "q": 3,
        "label": "p"
      }
    ]
  },
  "math-g10-p1-b-4-2": {
    "title": "The graph of f",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -14,
      6
    ],
    "curves": [
      {
        "kind": "line",
        "m": 1,
        "c": -4,
        "label": "f"
      }
    ]
  },
  "math-g10-p1-b-4-2-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -52,
      48
    ],
    "curves": [
      {
        "kind": "line",
        "m": 5,
        "c": -2
      }
    ]
  },
  "math-g10-p1-b-4-3": {
    "title": "The graph of f",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -14,
      6
    ],
    "curves": [
      {
        "kind": "line",
        "m": 1,
        "c": -4,
        "label": "f"
      }
    ]
  },
  "math-g10-p1-b-4-4": {
    "title": "The graph of g",
    "xRange": [
      -3,
      6
    ],
    "yRange": [
      -9,
      17
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -3,
        "c": -4,
        "label": "g"
      }
    ]
  },
  "math-g10-p1-b-4-4-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      8
    ],
    "yRange": [
      -9,
      22
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -6,
        "c": 3
      }
    ]
  },
  "math-g10-p1-b-4-5": {
    "title": "The graph of g",
    "xRange": [
      -3,
      6
    ],
    "yRange": [
      -9,
      17
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -3,
        "c": -4,
        "label": "g"
      }
    ]
  },
  "math-g10-p1-b-4-9": {
    "title": "The graph of p",
    "xRange": [
      -5,
      9
    ],
    "yRange": [
      -3,
      5
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 3,
        "p": 2,
        "q": 1,
        "label": "p"
      }
    ]
  },
  "math-g10-p1-c-4-2": {
    "title": "The graph of f",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -15,
      5
    ],
    "curves": [
      {
        "kind": "line",
        "m": 1,
        "c": -5,
        "label": "f"
      }
    ]
  },
  "math-g10-p1-c-4-3": {
    "title": "The graph of f",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -15,
      5
    ],
    "curves": [
      {
        "kind": "line",
        "m": 1,
        "c": -5,
        "label": "f"
      }
    ]
  },
  "math-g10-p1-c-4-4": {
    "title": "The graph of g",
    "xRange": [
      -3,
      7
    ],
    "yRange": [
      -12,
      19
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -4,
        "c": -5,
        "label": "g"
      }
    ]
  },
  "math-g10-p1-c-4-4-r": {
    "title": "The graph in this question",
    "xRange": [
      -4,
      10
    ],
    "yRange": [
      -10,
      2
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 4,
        "p": 3,
        "q": -5
      }
    ]
  },
  "math-g10-p1-c-4-5": {
    "title": "The graph of g",
    "xRange": [
      -3,
      7
    ],
    "yRange": [
      -12,
      19
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -4,
        "c": -5,
        "label": "g"
      }
    ]
  },
  "math-g10-p1-c-4-9": {
    "title": "The graph of p",
    "xRange": [
      -4,
      10
    ],
    "yRange": [
      -3,
      7
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 4,
        "p": 3,
        "q": 2,
        "label": "p"
      }
    ]
  },
  "math-g11-p1-20-4-1-r": {
    "title": "The graph in this question",
    "xRange": [
      -7,
      7
    ],
    "yRange": [
      -11,
      2
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 5,
        "p": 0,
        "q": -5
      }
    ]
  },
  "math-g11-p1-20-4-10-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      12
    ],
    "yRange": [
      -12,
      2
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 6,
        "p": 5,
        "q": -5
      }
    ]
  },
  "math-g11-p1-20-4-2": {
    "title": "The graph of g",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -117,
      63
    ],
    "curves": [
      {
        "kind": "line",
        "m": 9,
        "c": -27,
        "label": "g"
      }
    ]
  },
  "math-g11-p1-20-4-3": {
    "title": "The graph of h",
    "xRange": [
      -8,
      11
    ],
    "yRange": [
      -54,
      59
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -3,
        "c": -40,
        "label": "h"
      }
    ]
  },
  "math-g11-p1-20-4-4": {
    "title": "The graph of f",
    "xRange": [
      -2,
      15
    ],
    "yRange": [
      -127,
      24
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": -1,
        "b": 18,
        "c": -72,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-20-4-4-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -52,
      48
    ],
    "curves": [
      {
        "kind": "line",
        "m": 5,
        "c": -2
      }
    ]
  },
  "math-g11-p1-20-4-5-r": {
    "title": "The graph in this question",
    "xRange": [
      -1,
      9
    ],
    "yRange": [
      -9,
      22
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -8,
        "c": 10
      }
    ]
  },
  "math-g11-p1-20-4-6": {
    "title": "The graph of f",
    "xRange": [
      -2,
      15
    ],
    "yRange": [
      -6,
      13
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 10,
        "p": 8,
        "q": 4,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-20-4-7-r": {
    "title": "The graph in this question",
    "xRange": [
      -3,
      11
    ],
    "yRange": [
      -11,
      2
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 5,
        "p": 4,
        "q": -5
      }
    ]
  },
  "math-g11-p1-20-4-8": {
    "title": "The graph of f",
    "xRange": [
      -4,
      2
    ],
    "yRange": [
      -9,
      17
    ],
    "curves": [
      {
        "kind": "exponential",
        "a": 1,
        "b": 7,
        "q": -5,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-20-4-8-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -62,
      58
    ],
    "curves": [
      {
        "kind": "line",
        "m": 6,
        "c": -2
      }
    ]
  },
  "math-g11-p1-20-4-9": {
    "title": "The graph of f",
    "xRange": [
      -2,
      14
    ],
    "yRange": [
      -26,
      75
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -14,
        "c": 33,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-20-4-9-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      10
    ],
    "yRange": [
      -12,
      49
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -10,
        "c": 19
      }
    ]
  },
  "math-g11-p1-21-4-1-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -62,
      58
    ],
    "curves": [
      {
        "kind": "line",
        "m": 6,
        "c": -2
      }
    ]
  },
  "math-g11-p1-21-4-10-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      14
    ],
    "yRange": [
      -13,
      3
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 8,
        "p": 7,
        "q": -5
      }
    ]
  },
  "math-g11-p1-21-4-2": {
    "title": "The graph of g",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -104,
      56
    ],
    "curves": [
      {
        "kind": "line",
        "m": 8,
        "c": -24,
        "label": "g"
      }
    ]
  },
  "math-g11-p1-21-4-3": {
    "title": "The graph of h",
    "xRange": [
      -9,
      7
    ],
    "yRange": [
      -33,
      47
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 2,
        "c": -24,
        "label": "h"
      }
    ]
  },
  "math-g11-p1-21-4-4": {
    "title": "The graph of f",
    "xRange": [
      -2,
      14
    ],
    "yRange": [
      -103,
      21
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": -1,
        "b": 16,
        "c": -55,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-21-4-4-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -72,
      68
    ],
    "curves": [
      {
        "kind": "line",
        "m": 7,
        "c": -2
      }
    ]
  },
  "math-g11-p1-21-4-5-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      11
    ],
    "yRange": [
      -14,
      66
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -12,
        "c": 30
      }
    ]
  },
  "math-g11-p1-21-4-6": {
    "title": "The graph of f",
    "xRange": [
      -2,
      14
    ],
    "yRange": [
      -6,
      12
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 9,
        "p": 7,
        "q": 3,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-21-4-7-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      13
    ],
    "yRange": [
      -12,
      2
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 7,
        "p": 6,
        "q": -5
      }
    ]
  },
  "math-g11-p1-21-4-8": {
    "title": "The graph of f",
    "xRange": [
      -4,
      2
    ],
    "yRange": [
      -7,
      14
    ],
    "curves": [
      {
        "kind": "exponential",
        "a": 1,
        "b": 6,
        "q": -4,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-21-4-8-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -82,
      78
    ],
    "curves": [
      {
        "kind": "line",
        "m": 8,
        "c": -2
      }
    ]
  },
  "math-g11-p1-21-4-9": {
    "title": "The graph of f",
    "xRange": [
      -2,
      13
    ],
    "yRange": [
      -22,
      58
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -12,
        "c": 22,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-21-4-9-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      12
    ],
    "yRange": [
      -16,
      85
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -14,
        "c": 43
      }
    ]
  },
  "math-g11-p1-22-4-10-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      16
    ],
    "yRange": [
      -8,
      1
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 2,
        "p": 9,
        "q": -5
      }
    ]
  },
  "math-g11-p1-22-4-2": {
    "title": "The graph of g",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -91,
      49
    ],
    "curves": [
      {
        "kind": "line",
        "m": 7,
        "c": -21,
        "label": "g"
      }
    ]
  },
  "math-g11-p1-22-4-2-r": {
    "title": "The graph in this question",
    "xRange": [
      -7,
      7
    ],
    "yRange": [
      -12,
      2
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 6,
        "p": 0,
        "q": -5
      }
    ]
  },
  "math-g11-p1-22-4-3": {
    "title": "The graph of h",
    "xRange": [
      -8,
      9
    ],
    "yRange": [
      -39,
      51
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -1,
        "c": -30,
        "label": "h"
      }
    ]
  },
  "math-g11-p1-22-4-4": {
    "title": "The graph of f",
    "xRange": [
      -2,
      13
    ],
    "yRange": [
      -82,
      19
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": -1,
        "b": 14,
        "c": -40,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-22-4-4-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -92,
      88
    ],
    "curves": [
      {
        "kind": "line",
        "m": 9,
        "c": -2
      }
    ]
  },
  "math-g11-p1-22-4-5-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      13
    ],
    "yRange": [
      -18,
      106
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -16,
        "c": 58
      }
    ]
  },
  "math-g11-p1-22-4-6": {
    "title": "The graph of f",
    "xRange": [
      -2,
      13
    ],
    "yRange": [
      -7,
      9
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 8,
        "p": 6,
        "q": 1,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-22-4-7-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      15
    ],
    "yRange": [
      -14,
      3
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 9,
        "p": 8,
        "q": -5
      }
    ]
  },
  "math-g11-p1-22-4-8": {
    "title": "The graph of f",
    "xRange": [
      -4,
      5
    ],
    "yRange": [
      -11,
      15
    ],
    "curves": [
      {
        "kind": "exponential",
        "a": 1,
        "b": 2,
        "q": -7,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-22-4-8-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -102,
      98
    ],
    "curves": [
      {
        "kind": "line",
        "m": 10,
        "c": -2
      }
    ]
  },
  "math-g11-p1-22-4-9": {
    "title": "The graph of f",
    "xRange": [
      -2,
      11
    ],
    "yRange": [
      -19,
      42
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -10,
        "c": 12,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-22-4-9-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      14
    ],
    "yRange": [
      -21,
      130
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -18,
        "c": 75
      }
    ]
  },
  "math-g11-p1-23-4-10-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      18
    ],
    "yRange": [
      -9,
      1
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 4,
        "p": 11,
        "q": -5
      }
    ]
  },
  "math-g11-p1-23-4-2": {
    "title": "The graph of g",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -78,
      42
    ],
    "curves": [
      {
        "kind": "line",
        "m": 6,
        "c": -18,
        "label": "g"
      }
    ]
  },
  "math-g11-p1-23-4-2-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -72,
      68
    ],
    "curves": [
      {
        "kind": "line",
        "m": 7,
        "c": -2
      }
    ]
  },
  "math-g11-p1-23-4-3": {
    "title": "The graph of h",
    "xRange": [
      -9,
      6
    ],
    "yRange": [
      -27,
      43
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 3,
        "c": -18,
        "label": "h"
      }
    ]
  },
  "math-g11-p1-23-4-4": {
    "title": "The graph of f",
    "xRange": [
      -2,
      12
    ],
    "yRange": [
      -63,
      17
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": -1,
        "b": 12,
        "c": -27,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-23-4-4-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -112,
      108
    ],
    "curves": [
      {
        "kind": "line",
        "m": 11,
        "c": -2
      }
    ]
  },
  "math-g11-p1-23-4-5-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      16
    ],
    "yRange": [
      -24,
      156
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -20,
        "c": 94
      }
    ]
  },
  "math-g11-p1-23-4-6": {
    "title": "The graph of f",
    "xRange": [
      -2,
      12
    ],
    "yRange": [
      -6,
      10
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 7,
        "p": 5,
        "q": 2,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-23-4-7-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      17
    ],
    "yRange": [
      -8,
      1
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 3,
        "p": 10,
        "q": -5
      }
    ]
  },
  "math-g11-p1-23-4-8": {
    "title": "The graph of f",
    "xRange": [
      -4,
      3
    ],
    "yRange": [
      -11,
      55
    ],
    "curves": [
      {
        "kind": "exponential",
        "a": 1,
        "b": 5,
        "q": -3,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-23-4-8-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -122,
      118
    ],
    "curves": [
      {
        "kind": "line",
        "m": 12,
        "c": -2
      }
    ]
  },
  "math-g11-p1-23-4-9": {
    "title": "The graph of f",
    "xRange": [
      -2,
      10
    ],
    "yRange": [
      -16,
      30
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -8,
        "c": 5,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-23-4-9-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      17
    ],
    "yRange": [
      -27,
      184
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -22,
        "c": 115
      }
    ]
  },
  "math-g11-p1-24-4-10-r": {
    "title": "The graph in this question",
    "xRange": [
      -5,
      9
    ],
    "yRange": [
      -9,
      1
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 4,
        "p": 2,
        "q": -4
      }
    ]
  },
  "math-g11-p1-24-4-2": {
    "title": "The graph of g",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -70,
      30
    ],
    "curves": [
      {
        "kind": "line",
        "m": 5,
        "c": -20,
        "label": "g"
      }
    ]
  },
  "math-g11-p1-24-4-3": {
    "title": "The graph of h",
    "xRange": [
      -10,
      6
    ],
    "yRange": [
      -33,
      47
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 4,
        "c": -21,
        "label": "h"
      }
    ]
  },
  "math-g11-p1-24-4-4": {
    "title": "The graph of f",
    "xRange": [
      -2,
      11
    ],
    "yRange": [
      -46,
      15
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": -1,
        "b": 10,
        "c": -16,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-24-4-4-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -131,
      127
    ],
    "curves": [
      {
        "kind": "line",
        "m": 13,
        "c": -2
      }
    ]
  },
  "math-g11-p1-24-4-5-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      18
    ],
    "yRange": [
      -30,
      214
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -24,
        "c": 138
      }
    ]
  },
  "math-g11-p1-24-4-6": {
    "title": "The graph of f",
    "xRange": [
      -10,
      4
    ],
    "yRange": [
      -9,
      5
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 6,
        "p": -3,
        "q": -2,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-24-4-7-r": {
    "title": "The graph in this question",
    "xRange": [
      -6,
      8
    ],
    "yRange": [
      -8,
      1
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 3,
        "p": 1,
        "q": -4
      }
    ]
  },
  "math-g11-p1-24-4-8": {
    "title": "The graph of f",
    "xRange": [
      -4,
      3
    ],
    "yRange": [
      -11,
      28
    ],
    "curves": [
      {
        "kind": "exponential",
        "a": 1,
        "b": 4,
        "q": -6,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-24-4-8-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -141,
      137
    ],
    "curves": [
      {
        "kind": "line",
        "m": 14,
        "c": -2
      }
    ]
  },
  "math-g11-p1-24-4-9": {
    "title": "The graph of f",
    "xRange": [
      -9,
      3
    ],
    "yRange": [
      -15,
      31
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 6,
        "c": -1,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-24-4-9-r": {
    "title": "The graph in this question",
    "xRange": [
      -4,
      6
    ],
    "yRange": [
      -8,
      23
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -2,
        "c": -4
      }
    ]
  },
  "math-g11-p1-25-4-1-r": {
    "title": "The graph in this question",
    "xRange": [
      -7,
      7
    ],
    "yRange": [
      -13,
      3
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 7,
        "p": 0,
        "q": -5
      }
    ]
  },
  "math-g11-p1-25-4-10-r": {
    "title": "The graph in this question",
    "xRange": [
      -3,
      11
    ],
    "yRange": [
      -11,
      3
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 6,
        "p": 4,
        "q": -4
      }
    ]
  },
  "math-g11-p1-25-4-2": {
    "title": "The graph of g",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -56,
      24
    ],
    "curves": [
      {
        "kind": "line",
        "m": 4,
        "c": -16,
        "label": "g"
      }
    ]
  },
  "math-g11-p1-25-4-3": {
    "title": "The graph of h",
    "xRange": [
      -6,
      8
    ],
    "yRange": [
      -22,
      39
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -2,
        "c": -15,
        "label": "h"
      }
    ]
  },
  "math-g11-p1-25-4-4": {
    "title": "The graph of f",
    "xRange": [
      -1,
      7
    ],
    "yRange": [
      -14,
      6
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": -1,
        "b": 6,
        "c": -5,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-25-4-4-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -23,
      17
    ],
    "curves": [
      {
        "kind": "line",
        "m": 2,
        "c": -3
      }
    ]
  },
  "math-g11-p1-25-4-5-r": {
    "title": "The graph in this question",
    "xRange": [
      -3,
      7
    ],
    "yRange": [
      -8,
      23
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -4,
        "c": -1
      }
    ]
  },
  "math-g11-p1-25-4-6": {
    "title": "The graph of f",
    "xRange": [
      -5,
      9
    ],
    "yRange": [
      -2,
      10
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 5,
        "p": 2,
        "q": 4,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-25-4-7-r": {
    "title": "The graph in this question",
    "xRange": [
      -4,
      10
    ],
    "yRange": [
      -10,
      2
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 5,
        "p": 3,
        "q": -4
      }
    ]
  },
  "math-g11-p1-25-4-8": {
    "title": "The graph of f",
    "xRange": [
      -4,
      3
    ],
    "yRange": [
      -5,
      15
    ],
    "curves": [
      {
        "kind": "exponential",
        "a": 1,
        "b": 3,
        "q": -2,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-25-4-8-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -33,
      27
    ],
    "curves": [
      {
        "kind": "line",
        "m": 3,
        "c": -3
      }
    ]
  },
  "math-g11-p1-25-4-9": {
    "title": "The graph of f",
    "xRange": [
      -3,
      7
    ],
    "yRange": [
      -12,
      19
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -4,
        "c": -5,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-25-4-9-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      8
    ],
    "yRange": [
      -8,
      23
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -6,
        "c": 4
      }
    ]
  },
  "math-g11-p1-a-4-1-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -82,
      78
    ],
    "curves": [
      {
        "kind": "line",
        "m": 8,
        "c": -2
      }
    ]
  },
  "math-g11-p1-a-4-10-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      13
    ],
    "yRange": [
      -12,
      4
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 8,
        "p": 6,
        "q": -4
      }
    ]
  },
  "math-g11-p1-a-4-2": {
    "title": "The graph of g",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -28,
      12
    ],
    "curves": [
      {
        "kind": "line",
        "m": 2,
        "c": -8,
        "label": "g"
      }
    ]
  },
  "math-g11-p1-a-4-3": {
    "title": "The graph of h",
    "xRange": [
      -4,
      6
    ],
    "yRange": [
      -12,
      19
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -2,
        "c": -8,
        "label": "h"
      }
    ]
  },
  "math-g11-p1-a-4-4": {
    "title": "The graph of f",
    "xRange": [
      -1,
      7
    ],
    "yRange": [
      -14,
      6
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": -1,
        "b": 6,
        "c": -5,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-a-4-4-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -43,
      37
    ],
    "curves": [
      {
        "kind": "line",
        "m": 4,
        "c": -3
      }
    ]
  },
  "math-g11-p1-a-4-5-r": {
    "title": "The graph in this question",
    "xRange": [
      -1,
      9
    ],
    "yRange": [
      -8,
      23
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -8,
        "c": 11
      }
    ]
  },
  "math-g11-p1-a-4-6": {
    "title": "The graph of f",
    "xRange": [
      -5,
      9
    ],
    "yRange": [
      -3,
      5
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 3,
        "p": 2,
        "q": 1,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-a-4-7-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      12
    ],
    "yRange": [
      -12,
      4
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 7,
        "p": 5,
        "q": -4
      }
    ]
  },
  "math-g11-p1-a-4-8": {
    "title": "The graph of f",
    "xRange": [
      -4,
      3
    ],
    "yRange": [
      -7,
      13
    ],
    "curves": [
      {
        "kind": "exponential",
        "a": 1,
        "b": 3,
        "q": -4,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-a-4-8-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -53,
      47
    ],
    "curves": [
      {
        "kind": "line",
        "m": 5,
        "c": -3
      }
    ]
  },
  "math-g11-p1-a-4-9": {
    "title": "The graph of f",
    "xRange": [
      -2,
      6
    ],
    "yRange": [
      -3,
      22
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -4,
        "c": 7,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-a-4-9-r": {
    "title": "The graph in this question",
    "xRange": [
      -1,
      10
    ],
    "yRange": [
      -10,
      36
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -10,
        "c": 20
      }
    ]
  },
  "math-g11-p1-b-4-10-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      15
    ],
    "yRange": [
      -7,
      1
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 2,
        "p": 8,
        "q": -4
      }
    ]
  },
  "math-g11-p1-b-4-2": {
    "title": "The graph of g",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -39,
      21
    ],
    "curves": [
      {
        "kind": "line",
        "m": 3,
        "c": -9,
        "label": "g"
      }
    ]
  },
  "math-g11-p1-b-4-2-r": {
    "title": "The graph in this question",
    "xRange": [
      -7,
      7
    ],
    "yRange": [
      -14,
      4
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 8,
        "p": 0,
        "q": -5
      }
    ]
  },
  "math-g11-p1-b-4-3": {
    "title": "The graph of h",
    "xRange": [
      -7,
      6
    ],
    "yRange": [
      -18,
      36
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 1,
        "c": -12,
        "label": "h"
      }
    ]
  },
  "math-g11-p1-b-4-4": {
    "title": "The graph of f",
    "xRange": [
      -1,
      9
    ],
    "yRange": [
      -19,
      12
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": -1,
        "b": 8,
        "c": -7,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-b-4-4-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -63,
      57
    ],
    "curves": [
      {
        "kind": "line",
        "m": 6,
        "c": -3
      }
    ]
  },
  "math-g11-p1-b-4-5-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      11
    ],
    "yRange": [
      -13,
      67
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -12,
        "c": 31
      }
    ]
  },
  "math-g11-p1-b-4-6": {
    "title": "The graph of f",
    "xRange": [
      -8,
      6
    ],
    "yRange": [
      -8,
      2
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 4,
        "p": -1,
        "q": -3,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-b-4-7-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      14
    ],
    "yRange": [
      -13,
      5
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 9,
        "p": 7,
        "q": -4
      }
    ]
  },
  "math-g11-p1-b-4-8": {
    "title": "The graph of f",
    "xRange": [
      -4,
      5
    ],
    "yRange": [
      -9,
      17
    ],
    "curves": [
      {
        "kind": "exponential",
        "a": 1,
        "b": 2,
        "q": -5,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-b-4-8-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -73,
      67
    ],
    "curves": [
      {
        "kind": "line",
        "m": 7,
        "c": -3
      }
    ]
  },
  "math-g11-p1-b-4-9": {
    "title": "The graph of f",
    "xRange": [
      -5,
      3
    ],
    "yRange": [
      -6,
      14
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 2,
        "c": -3,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-b-4-9-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      12
    ],
    "yRange": [
      -15,
      86
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -14,
        "c": 44
      }
    ]
  },
  "math-g11-p1-c-4-10-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      17
    ],
    "yRange": [
      -8,
      1
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 4,
        "p": 10,
        "q": -4
      }
    ]
  },
  "math-g11-p1-c-4-2": {
    "title": "The graph of g",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -52,
      28
    ],
    "curves": [
      {
        "kind": "line",
        "m": 4,
        "c": -12,
        "label": "g"
      }
    ]
  },
  "math-g11-p1-c-4-2-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -92,
      88
    ],
    "curves": [
      {
        "kind": "line",
        "m": 9,
        "c": -2
      }
    ]
  },
  "math-g11-p1-c-4-3": {
    "title": "The graph of h",
    "xRange": [
      -5,
      8
    ],
    "yRange": [
      -18,
      36
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -3,
        "c": -10,
        "label": "h"
      }
    ]
  },
  "math-g11-p1-c-4-4": {
    "title": "The graph of f",
    "xRange": [
      -1,
      9
    ],
    "yRange": [
      -37,
      9
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": -1,
        "b": 10,
        "c": -21,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-c-4-4-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -83,
      77
    ],
    "curves": [
      {
        "kind": "line",
        "m": 8,
        "c": -3
      }
    ]
  },
  "math-g11-p1-c-4-5-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      13
    ],
    "yRange": [
      -17,
      107
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -16,
        "c": 59
      }
    ]
  },
  "math-g11-p1-c-4-6": {
    "title": "The graph of f",
    "xRange": [
      -4,
      10
    ],
    "yRange": [
      -8,
      4
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 5,
        "p": 3,
        "q": -2,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-c-4-7-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      16
    ],
    "yRange": [
      -7,
      1
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 3,
        "p": 9,
        "q": -4
      }
    ]
  },
  "math-g11-p1-c-4-8": {
    "title": "The graph of f",
    "xRange": [
      -4,
      3
    ],
    "yRange": [
      -11,
      28
    ],
    "curves": [
      {
        "kind": "exponential",
        "a": 1,
        "b": 4,
        "q": -6,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-c-4-8-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -93,
      87
    ],
    "curves": [
      {
        "kind": "line",
        "m": 9,
        "c": -3
      }
    ]
  },
  "math-g11-p1-c-4-9": {
    "title": "The graph of f",
    "xRange": [
      -1,
      7
    ],
    "yRange": [
      -3,
      21
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -6,
        "c": 11,
        "label": "f"
      }
    ]
  },
  "math-g11-p1-c-4-9-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      14
    ],
    "yRange": [
      -20,
      131
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -18,
        "c": 76
      }
    ]
  },
  "math-p1-20-4-2": {
    "title": "The graph of g",
    "xRange": [
      -11,
      7
    ],
    "yRange": [
      -46,
      55
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 4,
        "c": -32,
        "label": "g"
      }
    ]
  },
  "math-p1-20-4-2-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -103,
      97
    ],
    "curves": [
      {
        "kind": "line",
        "m": 10,
        "c": -3
      }
    ]
  },
  "math-p1-20-4-3": {
    "title": "The graph of h",
    "xRange": [
      -2,
      16
    ],
    "yRange": [
      -27,
      153
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -20,
        "c": 91,
        "label": "h"
      }
    ]
  },
  "math-p1-20-4-3-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      15
    ],
    "yRange": [
      -23,
      157
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -20,
        "c": 95
      }
    ]
  },
  "math-p1-20-4-5": {
    "title": "The graph of f",
    "xRange": [
      -4,
      2
    ],
    "yRange": [
      -8,
      18
    ],
    "curves": [
      {
        "kind": "exponential",
        "a": 1,
        "b": 7,
        "q": -4,
        "label": "f"
      }
    ]
  },
  "math-p1-20-4-6": {
    "title": "The graph of f",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -104,
      56
    ],
    "curves": [
      {
        "kind": "line",
        "m": 8,
        "c": -24,
        "label": "f"
      }
    ]
  },
  "math-p1-20-4-9": {
    "title": "The graph of f",
    "xRange": [
      -15,
      2
    ],
    "yRange": [
      -22,
      129
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 18,
        "c": 74,
        "label": "f"
      }
    ]
  },
  "math-p1-21-4-2": {
    "title": "The graph of g",
    "xRange": [
      -10,
      7
    ],
    "yRange": [
      -39,
      51
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 3,
        "c": -28,
        "label": "g"
      }
    ]
  },
  "math-p1-21-4-2-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      18
    ],
    "yRange": [
      -8,
      1
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 5,
        "p": 11,
        "q": -4
      }
    ]
  },
  "math-p1-21-4-3": {
    "title": "The graph of h",
    "xRange": [
      -2,
      15
    ],
    "yRange": [
      -24,
      127
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -18,
        "c": 72,
        "label": "h"
      }
    ]
  },
  "math-p1-21-4-3-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -113,
      107
    ],
    "curves": [
      {
        "kind": "line",
        "m": 11,
        "c": -3
      }
    ]
  },
  "math-p1-21-4-5": {
    "title": "The graph of f",
    "xRange": [
      -4,
      2
    ],
    "yRange": [
      -6,
      15
    ],
    "curves": [
      {
        "kind": "exponential",
        "a": 1,
        "b": 6,
        "q": -3,
        "label": "f"
      }
    ]
  },
  "math-p1-21-4-6": {
    "title": "The graph of f",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -91,
      49
    ],
    "curves": [
      {
        "kind": "line",
        "m": 7,
        "c": -21,
        "label": "f"
      }
    ]
  },
  "math-p1-21-4-9": {
    "title": "The graph of f",
    "xRange": [
      -2,
      13
    ],
    "yRange": [
      -13,
      119
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -16,
        "c": 70,
        "label": "f"
      }
    ]
  },
  "math-p1-22-4-2": {
    "title": "The graph of g",
    "xRange": [
      -9,
      7
    ],
    "yRange": [
      -33,
      47
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 2,
        "c": -24,
        "label": "g"
      }
    ]
  },
  "math-p1-22-4-2-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      16
    ],
    "yRange": [
      -26,
      185
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -22,
        "c": 116
      }
    ]
  },
  "math-p1-22-4-3": {
    "title": "The graph of h",
    "xRange": [
      -2,
      14
    ],
    "yRange": [
      -21,
      103
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -16,
        "c": 55,
        "label": "h"
      }
    ]
  },
  "math-p1-22-4-3-r": {
    "title": "The graph in this question",
    "xRange": [
      -6,
      8
    ],
    "yRange": [
      -8,
      2
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 4,
        "p": 1,
        "q": -3
      }
    ]
  },
  "math-p1-22-4-5": {
    "title": "The graph of f",
    "xRange": [
      -4,
      5
    ],
    "yRange": [
      -10,
      16
    ],
    "curves": [
      {
        "kind": "exponential",
        "a": 1,
        "b": 2,
        "q": -6,
        "label": "f"
      }
    ]
  },
  "math-p1-22-4-6": {
    "title": "The graph of f",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -78,
      42
    ],
    "curves": [
      {
        "kind": "line",
        "m": 6,
        "c": -18,
        "label": "f"
      }
    ]
  },
  "math-p1-22-4-9": {
    "title": "The graph of f",
    "xRange": [
      -11,
      2
    ],
    "yRange": [
      -12,
      89
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 14,
        "c": 47,
        "label": "f"
      }
    ]
  },
  "math-p1-23-4-2": {
    "title": "The graph of g",
    "xRange": [
      -7,
      8
    ],
    "yRange": [
      -27,
      43
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -1,
        "c": -20,
        "label": "g"
      }
    ]
  },
  "math-p1-23-4-2-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -123,
      117
    ],
    "curves": [
      {
        "kind": "line",
        "m": 12,
        "c": -3
      }
    ]
  },
  "math-p1-23-4-3": {
    "title": "The graph of h",
    "xRange": [
      -2,
      13
    ],
    "yRange": [
      -19,
      82
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -14,
        "c": 40,
        "label": "h"
      }
    ]
  },
  "math-p1-23-4-3-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      18
    ],
    "yRange": [
      -29,
      215
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -24,
        "c": 139
      }
    ]
  },
  "math-p1-23-4-5": {
    "title": "The graph of f",
    "xRange": [
      -4,
      3
    ],
    "yRange": [
      -5,
      15
    ],
    "curves": [
      {
        "kind": "exponential",
        "a": 1,
        "b": 3,
        "q": -2,
        "label": "f"
      }
    ]
  },
  "math-p1-23-4-6": {
    "title": "The graph of f",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -56,
      24
    ],
    "curves": [
      {
        "kind": "line",
        "m": 4,
        "c": -16,
        "label": "f"
      }
    ]
  },
  "math-p1-23-4-9": {
    "title": "The graph of f",
    "xRange": [
      -2,
      11
    ],
    "yRange": [
      -9,
      78
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -12,
        "c": 41,
        "label": "f"
      }
    ]
  },
  "math-p1-23-5-3": {
    "title": "The graph of f",
    "xRange": [
      -5,
      5
    ],
    "yRange": [
      -174,
      174
    ],
    "curves": [
      {
        "kind": "cubic",
        "a": 1,
        "b": 0,
        "c": 3,
        "d": 0,
        "label": "f"
      }
    ]
  },
  "math-p1-24-4-2": {
    "title": "The graph of g",
    "xRange": [
      -6,
      10
    ],
    "yRange": [
      -33,
      47
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -4,
        "c": -21,
        "label": "g"
      }
    ]
  },
  "math-p1-24-4-2-r": {
    "title": "The graph in this question",
    "xRange": [
      -5,
      9
    ],
    "yRange": [
      -9,
      3
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 5,
        "p": 2,
        "q": -3
      }
    ]
  },
  "math-p1-24-4-3": {
    "title": "The graph of h",
    "xRange": [
      -2,
      13
    ],
    "yRange": [
      -24,
      56
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -12,
        "c": 20,
        "label": "h"
      }
    ]
  },
  "math-p1-24-4-3-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -132,
      126
    ],
    "curves": [
      {
        "kind": "line",
        "m": 13,
        "c": -3
      }
    ]
  },
  "math-p1-24-4-5": {
    "title": "The graph of f",
    "xRange": [
      -4,
      3
    ],
    "yRange": [
      -10,
      29
    ],
    "curves": [
      {
        "kind": "exponential",
        "a": 1,
        "b": 4,
        "q": -5,
        "label": "f"
      }
    ]
  },
  "math-p1-24-4-6": {
    "title": "The graph of f",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -65,
      35
    ],
    "curves": [
      {
        "kind": "line",
        "m": 5,
        "c": -15,
        "label": "f"
      }
    ]
  },
  "math-p1-24-4-9": {
    "title": "The graph of f",
    "xRange": [
      -1,
      9
    ],
    "yRange": [
      -5,
      45
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -10,
        "c": 29,
        "label": "f"
      }
    ]
  },
  "math-p1-25-4-2": {
    "title": "The graph of g",
    "xRange": [
      -6,
      9
    ],
    "yRange": [
      -27,
      43
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -3,
        "c": -18,
        "label": "g"
      }
    ]
  },
  "math-p1-25-4-2-r": {
    "title": "The graph in this question",
    "xRange": [
      -3,
      5
    ],
    "yRange": [
      -6,
      14
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -2,
        "c": -3
      }
    ]
  },
  "math-p1-25-4-3": {
    "title": "The graph of h",
    "xRange": [
      -2,
      11
    ],
    "yRange": [
      -15,
      46
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -10,
        "c": 16,
        "label": "h"
      }
    ]
  },
  "math-p1-25-4-3-r": {
    "title": "The graph in this question",
    "xRange": [
      -4,
      10
    ],
    "yRange": [
      -10,
      4
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 6,
        "p": 3,
        "q": -3
      }
    ]
  },
  "math-p1-25-4-5": {
    "title": "The graph of f",
    "xRange": [
      -4,
      3
    ],
    "yRange": [
      -12,
      54
    ],
    "curves": [
      {
        "kind": "exponential",
        "a": 1,
        "b": 5,
        "q": -4,
        "label": "f"
      }
    ]
  },
  "math-p1-25-4-6": {
    "title": "The graph of f",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -30,
      10
    ],
    "curves": [
      {
        "kind": "line",
        "m": 2,
        "c": -10,
        "label": "f"
      }
    ]
  },
  "math-p1-25-4-9": {
    "title": "The graph of f",
    "xRange": [
      -8,
      1
    ],
    "yRange": [
      -6,
      25
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 8,
        "c": 13,
        "label": "f"
      }
    ]
  },
  "math-p1-a-4-2": {
    "title": "The graph of g",
    "xRange": [
      -4,
      5
    ],
    "yRange": [
      -9,
      17
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -1,
        "c": -6,
        "label": "g"
      }
    ]
  },
  "math-p1-a-4-2-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -142,
      136
    ],
    "curves": [
      {
        "kind": "line",
        "m": 14,
        "c": -3
      }
    ]
  },
  "math-p1-a-4-3": {
    "title": "The graph of h",
    "xRange": [
      -3,
      7
    ],
    "yRange": [
      -23,
      8
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": -1,
        "b": 4,
        "c": 1,
        "label": "h"
      }
    ]
  },
  "math-p1-a-4-3-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      6
    ],
    "yRange": [
      -6,
      14
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -4,
        "c": 0
      }
    ]
  },
  "math-p1-a-4-5": {
    "title": "The graph of f",
    "xRange": [
      -4,
      5
    ],
    "yRange": [
      -7,
      19
    ],
    "curves": [
      {
        "kind": "exponential",
        "a": 1,
        "b": 2,
        "q": -3,
        "label": "f"
      }
    ]
  },
  "math-p1-a-4-6": {
    "title": "The graph of f",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -15,
      25
    ],
    "curves": [
      {
        "kind": "line",
        "m": -2,
        "c": 5,
        "label": "f"
      }
    ]
  },
  "math-p1-a-4-9": {
    "title": "The graph of f",
    "xRange": [
      -3,
      5
    ],
    "yRange": [
      -14,
      6
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": -1,
        "b": 2,
        "c": 3,
        "label": "f"
      }
    ]
  },
  "math-p1-b-4-2": {
    "title": "The graph of g",
    "xRange": [
      -7,
      6
    ],
    "yRange": [
      -18,
      36
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 1,
        "c": -12,
        "label": "g"
      }
    ]
  },
  "math-p1-b-4-2-r": {
    "title": "The graph in this question",
    "xRange": [
      -3,
      11
    ],
    "yRange": [
      -11,
      5
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 7,
        "p": 4,
        "q": -3
      }
    ]
  },
  "math-p1-b-4-3": {
    "title": "The graph of h",
    "xRange": [
      -1,
      7
    ],
    "yRange": [
      -6,
      14
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -6,
        "c": 5,
        "label": "h"
      }
    ]
  },
  "math-p1-b-4-3-r": {
    "title": "The graph in this question",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -24,
      16
    ],
    "curves": [
      {
        "kind": "line",
        "m": 2,
        "c": -4
      }
    ]
  },
  "math-p1-b-4-5": {
    "title": "The graph of f",
    "xRange": [
      -4,
      3
    ],
    "yRange": [
      -3,
      19
    ],
    "curves": [
      {
        "kind": "exponential",
        "a": 1,
        "b": 3,
        "q": 2,
        "label": "f"
      }
    ]
  },
  "math-p1-b-4-6": {
    "title": "The graph of f",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -48,
      32
    ],
    "curves": [
      {
        "kind": "line",
        "m": 4,
        "c": -8,
        "label": "f"
      }
    ]
  },
  "math-p1-b-4-9": {
    "title": "The graph of f",
    "xRange": [
      -5,
      1
    ],
    "yRange": [
      -3,
      10
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 4,
        "c": 3,
        "label": "f"
      }
    ]
  },
  "math-p1-c-4-2": {
    "title": "The graph of g",
    "xRange": [
      -6,
      8
    ],
    "yRange": [
      -22,
      39
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -2,
        "c": -15,
        "label": "g"
      }
    ]
  },
  "math-p1-c-4-2-r": {
    "title": "The graph in this question",
    "xRange": [
      -1,
      7
    ],
    "yRange": [
      -6,
      14
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -6,
        "c": 5
      }
    ]
  },
  "math-p1-c-4-3": {
    "title": "The graph of h",
    "xRange": [
      -1,
      9
    ],
    "yRange": [
      -9,
      22
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -8,
        "c": 10,
        "label": "h"
      }
    ]
  },
  "math-p1-c-4-3-r": {
    "title": "The graph in this question",
    "xRange": [
      -2,
      12
    ],
    "yRange": [
      -12,
      6
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 8,
        "p": 5,
        "q": -3
      }
    ]
  },
  "math-p1-c-4-5": {
    "title": "The graph of f",
    "xRange": [
      -4,
      3
    ],
    "yRange": [
      -8,
      12
    ],
    "curves": [
      {
        "kind": "exponential",
        "a": 1,
        "b": 3,
        "q": -5,
        "label": "f"
      }
    ]
  },
  "math-p1-c-4-6": {
    "title": "The graph of f",
    "xRange": [
      -8,
      8
    ],
    "yRange": [
      -39,
      21
    ],
    "curves": [
      {
        "kind": "line",
        "m": 3,
        "c": -9,
        "label": "f"
      }
    ]
  },
  "math-p1-c-4-9": {
    "title": "The graph of f",
    "xRange": [
      -1,
      7
    ],
    "yRange": [
      -3,
      21
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -6,
        "c": 11,
        "label": "f"
      }
    ]
  },
  "mfun-c1": {
    "title": "The graph of f",
    "xRange": [
      -4,
      10
    ],
    "yRange": [
      -2,
      4
    ],
    "curves": [
      {
        "kind": "hyperbola",
        "a": 2,
        "p": 3,
        "q": 1,
        "label": "f"
      }
    ]
  },
  "mfun-m1": {
    "title": "The graph of f",
    "xRange": [
      -2,
      6
    ],
    "yRange": [
      -5,
      15
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": -4,
        "c": 1,
        "label": "f"
      }
    ]
  },
  "mfun-m2": {
    "title": "The graph of g",
    "xRange": [
      -4,
      5
    ],
    "yRange": [
      -3,
      23
    ],
    "curves": [
      {
        "kind": "exponential",
        "a": 1,
        "b": 2,
        "q": 1,
        "label": "g"
      }
    ]
  },
  "mth-cubic-1": {
    "title": "The graph of f",
    "xRange": [
      -5,
      5
    ],
    "yRange": [
      -148,
      52
    ],
    "curves": [
      {
        "kind": "cubic",
        "a": 1,
        "b": -3,
        "c": -9,
        "d": 27,
        "label": "f"
      }
    ]
  },
  "mth-transf-1": {
    "title": "The graph of f",
    "xRange": [
      -2,
      2
    ],
    "yRange": [
      -1,
      5
    ],
    "curves": [
      {
        "kind": "parabola",
        "a": 1,
        "b": 0,
        "c": 0,
        "label": "f"
      }
    ]
  }
}
