/* GENERATED by tools/derive-circuits.mts -- do not edit by hand.
 *
 * Which circuit belongs with which Physical Sciences question, read out of the
 * question's own words and checked against its own answer. Regenerate with
 * `npm run circuits:write`; `npm run check:circuits` fails if this file has
 * drifted from the corpus.
 */
import type { CircuitSpec } from '@/types'

/** Shown beside the question, as a paper prints it. */
export const derivedCircuits: Record<string, CircuitSpec> = {
  "psci-g11-p1-2020-7-2": {
    "title": "The circuit described in this question",
    "emf": 40,
    "elements": [
      {
        "kind": "resistor",
        "ohms": 8
      },
      {
        "kind": "resistor",
        "ohms": 12
      }
    ]
  },
  "psci-g11-p1-2020-7-3": {
    "title": "The circuit described in this question",
    "elements": [
      {
        "kind": "parallel",
        "of": [
          {
            "ohms": 10
          },
          {
            "ohms": 15
          }
        ]
      }
    ]
  },
  "psci-g11-p1-2020-7-4": {
    "title": "The circuit described in this question",
    "elements": [
      {
        "kind": "resistor",
        "ohms": 4
      },
      {
        "kind": "parallel",
        "of": [
          {
            "ohms": 10
          },
          {
            "ohms": 15
          }
        ]
      }
    ]
  },
  "psci-g11-p1-2021-7-2": {
    "title": "The circuit described in this question",
    "emf": 36,
    "elements": [
      {
        "kind": "resistor",
        "ohms": 7
      },
      {
        "kind": "resistor",
        "ohms": 11
      }
    ]
  },
  "psci-g11-p1-2021-7-3": {
    "title": "The circuit described in this question",
    "elements": [
      {
        "kind": "parallel",
        "of": [
          {
            "ohms": 6
          },
          {
            "ohms": 30
          }
        ]
      }
    ]
  },
  "psci-g11-p1-2021-7-4": {
    "title": "The circuit described in this question",
    "elements": [
      {
        "kind": "resistor",
        "ohms": 3
      },
      {
        "kind": "parallel",
        "of": [
          {
            "ohms": 6
          },
          {
            "ohms": 30
          }
        ]
      }
    ]
  },
  "psci-g11-p1-2022-7-2": {
    "title": "The circuit described in this question",
    "emf": 48,
    "elements": [
      {
        "kind": "resistor",
        "ohms": 9
      },
      {
        "kind": "resistor",
        "ohms": 15
      }
    ]
  },
  "psci-g11-p1-2022-7-3": {
    "title": "The circuit described in this question",
    "elements": [
      {
        "kind": "parallel",
        "of": [
          {
            "ohms": 12
          },
          {
            "ohms": 4
          }
        ]
      }
    ]
  },
  "psci-g11-p1-2022-7-4": {
    "title": "The circuit described in this question",
    "elements": [
      {
        "kind": "resistor",
        "ohms": 9
      },
      {
        "kind": "parallel",
        "of": [
          {
            "ohms": 12
          },
          {
            "ohms": 4
          }
        ]
      }
    ]
  },
  "psci-g11-p1-2023-7-2": {
    "title": "The circuit described in this question",
    "emf": 18,
    "elements": [
      {
        "kind": "resistor",
        "ohms": 5
      },
      {
        "kind": "resistor",
        "ohms": 7
      }
    ]
  },
  "psci-g11-p1-2023-7-3": {
    "title": "The circuit described in this question",
    "elements": [
      {
        "kind": "parallel",
        "of": [
          {
            "ohms": 8
          },
          {
            "ohms": 24
          }
        ]
      }
    ]
  },
  "psci-g11-p1-2023-7-4": {
    "title": "The circuit described in this question",
    "elements": [
      {
        "kind": "resistor",
        "ohms": 5
      },
      {
        "kind": "parallel",
        "of": [
          {
            "ohms": 8
          },
          {
            "ohms": 24
          }
        ]
      }
    ]
  },
  "psci-g11-p1-2024-7-2": {
    "title": "The circuit described in this question",
    "emf": 32,
    "elements": [
      {
        "kind": "resistor",
        "ohms": 6
      },
      {
        "kind": "resistor",
        "ohms": 10
      }
    ]
  },
  "psci-g11-p1-2024-7-3": {
    "title": "The circuit described in this question",
    "elements": [
      {
        "kind": "parallel",
        "of": [
          {
            "ohms": 5
          },
          {
            "ohms": 20
          }
        ]
      }
    ]
  },
  "psci-g11-p1-2024-7-4": {
    "title": "The circuit described in this question",
    "elements": [
      {
        "kind": "resistor",
        "ohms": 5
      },
      {
        "kind": "parallel",
        "of": [
          {
            "ohms": 5
          },
          {
            "ohms": 20
          }
        ]
      }
    ]
  },
  "psci-g11-p1-2025-7-2": {
    "title": "The circuit described in this question",
    "emf": 24,
    "elements": [
      {
        "kind": "resistor",
        "ohms": 3
      },
      {
        "kind": "resistor",
        "ohms": 9
      }
    ]
  },
  "psci-g11-p1-2025-7-3": {
    "title": "The circuit described in this question",
    "elements": [
      {
        "kind": "parallel",
        "of": [
          {
            "ohms": 4
          },
          {
            "ohms": 6
          }
        ]
      }
    ]
  },
  "psci-g11-p1-2025-7-4": {
    "title": "The circuit described in this question",
    "elements": [
      {
        "kind": "resistor",
        "ohms": 3
      },
      {
        "kind": "parallel",
        "of": [
          {
            "ohms": 4
          },
          {
            "ohms": 6
          }
        ]
      }
    ]
  },
  "psci-g11-p1-seta-7-2": {
    "title": "The circuit described in this question",
    "emf": 12,
    "elements": [
      {
        "kind": "resistor",
        "ohms": 4
      },
      {
        "kind": "resistor",
        "ohms": 8
      }
    ]
  },
  "psci-g11-p1-seta-7-3": {
    "title": "The circuit described in this question",
    "elements": [
      {
        "kind": "parallel",
        "of": [
          {
            "ohms": 6
          },
          {
            "ohms": 12
          }
        ]
      }
    ]
  },
  "psci-g11-p1-seta-7-4": {
    "title": "The circuit described in this question",
    "elements": [
      {
        "kind": "resistor",
        "ohms": 4
      },
      {
        "kind": "parallel",
        "of": [
          {
            "ohms": 6
          },
          {
            "ohms": 12
          }
        ]
      }
    ]
  },
  "psci-g11-p1-setb-7-2": {
    "title": "The circuit described in this question",
    "emf": 15,
    "elements": [
      {
        "kind": "resistor",
        "ohms": 5
      },
      {
        "kind": "resistor",
        "ohms": 10
      }
    ]
  },
  "psci-g11-p1-setb-7-3": {
    "title": "The circuit described in this question",
    "elements": [
      {
        "kind": "parallel",
        "of": [
          {
            "ohms": 4
          },
          {
            "ohms": 12
          }
        ]
      }
    ]
  },
  "psci-g11-p1-setb-7-4": {
    "title": "The circuit described in this question",
    "elements": [
      {
        "kind": "resistor",
        "ohms": 3
      },
      {
        "kind": "parallel",
        "of": [
          {
            "ohms": 8
          },
          {
            "ohms": 8
          }
        ]
      }
    ]
  },
  "psci-g11-p1-setc-7-2": {
    "title": "The circuit described in this question",
    "emf": 18,
    "elements": [
      {
        "kind": "resistor",
        "ohms": 6
      },
      {
        "kind": "resistor",
        "ohms": 12
      }
    ]
  },
  "psci-g11-p1-setc-7-3": {
    "title": "The circuit described in this question",
    "elements": [
      {
        "kind": "parallel",
        "of": [
          {
            "ohms": 9
          },
          {
            "ohms": 18
          }
        ]
      }
    ]
  },
  "psci-g11-p1-setc-7-4": {
    "title": "The circuit described in this question",
    "elements": [
      {
        "kind": "resistor",
        "ohms": 2
      },
      {
        "kind": "parallel",
        "of": [
          {
            "ohms": 10
          },
          {
            "ohms": 15
          }
        ]
      }
    ]
  },
  "psci-p1-2020-6-3": {
    "title": "The circuit described in this question",
    "emf": 12,
    "elements": [
      {
        "kind": "parallel",
        "of": [
          {
            "ohms": 10
          },
          {
            "ohms": 15
          }
        ]
      }
    ]
  },
  "psci-p1-2020-6-4": {
    "title": "The circuit described in this question",
    "emf": 10,
    "internalResistance": 0.5,
    "elements": [
      {
        "kind": "resistor",
        "ohms": 4.5
      }
    ]
  },
  "psci-p1-2020-6-5": {
    "title": "The circuit described in this question",
    "emf": 10,
    "internalResistance": 0.5,
    "elements": [
      {
        "kind": "resistor",
        "ohms": 4.5
      }
    ]
  },
  "psci-p1-2021-6-3": {
    "title": "The circuit described in this question",
    "emf": 24,
    "elements": [
      {
        "kind": "parallel",
        "of": [
          {
            "ohms": 8
          },
          {
            "ohms": 8
          }
        ]
      }
    ]
  },
  "psci-p1-2021-6-4": {
    "title": "The circuit described in this question",
    "emf": 9,
    "internalResistance": 0.5,
    "elements": [
      {
        "kind": "resistor",
        "ohms": 2.5
      }
    ]
  },
  "psci-p1-2021-6-5": {
    "title": "The circuit described in this question",
    "emf": 9,
    "internalResistance": 0.5,
    "elements": [
      {
        "kind": "resistor",
        "ohms": 2.5
      }
    ]
  },
  "psci-p1-2022-6-3": {
    "title": "The circuit described in this question",
    "emf": 9.6,
    "elements": [
      {
        "kind": "parallel",
        "of": [
          {
            "ohms": 6
          },
          {
            "ohms": 24
          }
        ]
      }
    ]
  },
  "psci-p1-2022-6-4": {
    "title": "The circuit described in this question",
    "emf": 12,
    "internalResistance": 1,
    "elements": [
      {
        "kind": "resistor",
        "ohms": 5
      }
    ]
  },
  "psci-p1-2022-6-5": {
    "title": "The circuit described in this question",
    "emf": 12,
    "internalResistance": 1,
    "elements": [
      {
        "kind": "resistor",
        "ohms": 5
      }
    ]
  },
  "psci-p1-2023-6-3": {
    "title": "The circuit described in this question",
    "emf": 18,
    "elements": [
      {
        "kind": "parallel",
        "of": [
          {
            "ohms": 9
          },
          {
            "ohms": 18
          }
        ]
      }
    ]
  },
  "psci-p1-2023-6-4": {
    "title": "The circuit described in this question",
    "emf": 18,
    "internalResistance": 1,
    "elements": [
      {
        "kind": "resistor",
        "ohms": 8
      }
    ]
  },
  "psci-p1-2023-6-5": {
    "title": "The circuit described in this question",
    "emf": 18,
    "internalResistance": 1,
    "elements": [
      {
        "kind": "resistor",
        "ohms": 8
      }
    ]
  },
  "psci-p1-2024-6-3": {
    "title": "The circuit described in this question",
    "elements": [
      {
        "kind": "parallel",
        "of": [
          {
            "ohms": 5
          },
          {
            "ohms": 20
          }
        ]
      }
    ]
  },
  "psci-p1-2024-6-4": {
    "title": "The circuit described in this question",
    "emf": 10,
    "internalResistance": 0.2,
    "elements": [
      {
        "kind": "resistor",
        "ohms": 4.8
      }
    ]
  },
  "psci-p1-2024-6-5": {
    "title": "The circuit described in this question",
    "emf": 10,
    "internalResistance": 0.2,
    "elements": [
      {
        "kind": "resistor",
        "ohms": 4.8
      }
    ]
  },
  "psci-p1-2025-6-3": {
    "title": "The circuit described in this question",
    "elements": [
      {
        "kind": "parallel",
        "of": [
          {
            "ohms": 8
          },
          {
            "ohms": 8
          }
        ]
      }
    ]
  },
  "psci-p1-2025-6-4": {
    "title": "The circuit described in this question",
    "emf": 15,
    "internalResistance": 0.5,
    "elements": [
      {
        "kind": "resistor",
        "ohms": 2.5
      }
    ]
  },
  "psci-p1-2025-6-5": {
    "title": "The circuit described in this question",
    "emf": 15,
    "internalResistance": 0.5,
    "elements": [
      {
        "kind": "resistor",
        "ohms": 2.5
      }
    ]
  },
  "psci-p1-a-6-3": {
    "title": "The circuit described in this question",
    "elements": [
      {
        "kind": "parallel",
        "of": [
          {
            "ohms": 6
          },
          {
            "ohms": 12
          }
        ]
      }
    ]
  },
  "psci-p1-a-6-4": {
    "title": "The circuit described in this question",
    "emf": 12,
    "internalResistance": 0.5,
    "elements": [
      {
        "kind": "resistor",
        "ohms": 5.5
      }
    ]
  },
  "psci-p1-a-6-5": {
    "title": "The circuit described in this question",
    "emf": 12,
    "internalResistance": 0.5,
    "elements": [
      {
        "kind": "resistor",
        "ohms": 5.5
      }
    ]
  },
  "psci-p1-b-6-3": {
    "title": "The circuit described in this question",
    "elements": [
      {
        "kind": "parallel",
        "of": [
          {
            "ohms": 4
          },
          {
            "ohms": 6
          },
          {
            "ohms": 12
          }
        ]
      }
    ]
  },
  "psci-p1-b-6-4": {
    "title": "The circuit described in this question",
    "emf": 9,
    "internalResistance": 1,
    "elements": [
      {
        "kind": "resistor",
        "ohms": 8
      }
    ]
  },
  "psci-p1-b-6-5": {
    "title": "The circuit described in this question",
    "emf": 9,
    "internalResistance": 1,
    "elements": [
      {
        "kind": "resistor",
        "ohms": 8
      }
    ]
  },
  "psci-p1-c-6-4": {
    "title": "The circuit described in this question",
    "emf": 6,
    "internalResistance": 0.4,
    "elements": [
      {
        "kind": "resistor",
        "ohms": 2.6
      }
    ]
  },
  "psci-p1-c-6-5": {
    "title": "The circuit described in this question",
    "emf": 6,
    "internalResistance": 0.4,
    "elements": [
      {
        "kind": "resistor",
        "ohms": 2.6
      }
    ]
  },
  "psci-series-mt1": {
    "title": "The circuit described in this question",
    "emf": 12,
    "elements": [
      {
        "kind": "resistor",
        "ohms": 4
      },
      {
        "kind": "resistor",
        "ohms": 6
      }
    ]
  }
}

/** Shown only with the revealed answer: questions that ask for the drawing. */
export const derivedAnswerCircuits: Record<string, CircuitSpec> = {}
